import React from "react";
import { Link } from "gatsby";

const CookiePolicyPage = () => {
  return (
    <main>
      <style>
        {`
          .cky-banner-element {
            padding: 8px 30px;
            background: #F8F9FA;
            color: #858A8F;
            border: 1px solid #DEE2E6;
            box-sizing: border-box;
            border-radius: 2px;
            cursor: pointer;
          }
        `}
      </style>
      <h1 className="cookie-policy-h1">Cookie Policy</h1>
      <p>
        Effective Date: 26-Aug-2023 <br />
        Last Updated: 25-Aug-2023
      </p>
      <h5>What are cookies?</h5>
      <div className="cookie-policy-p">
        {/* Your cookie policy content */}
      </div>
      {/* Add the rest of your content */}
      <h5>How do we use cookies?</h5>
      <div className="cookie-policy-p">
        {/* More content */}
      </div>
      {/* Add the rest of your content */}
      <h5>Types of Cookies we use</h5>
      <div className="cky-audit-table-element">
        {/* Content */}
      </div>
      {/* Add the rest of your content */}
      <h5 style={{ marginBottom: "20px" }}>Manage cookie preferences</h5>
      <a className="cky-banner-element">Cookie Settings</a>
      <br />
      <div>
        {/* More content */}
      </div>
      <p className="cookie-policy-p">
        Cookie Policy Generated By{" "}
        <a
          target="_blank"
          href="https://www.cookieyes.com/?utm_source=CP&utm_medium=footer&utm_campaign=UW"
        >
          CookieYes - Cookie Policy Generator
        </a>
        .
      </p>
    </main>
  );
};

export default CookiePolicyPage;
export const Head = () => <title>Cookie Policy Page</title>